spring.application.name=estaciones

spring.config.import=file:secret.properties

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.jpa.database=${DATABASE}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}

# Actuator config
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.caches.enabled=true

# Redis (WSL)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.cache-names=estaciones_lista, estaciones

# Tiempo de vida del cache, Ej: 1 hora
spring.cache.redis.time-to-live=3600000
